name: 01 - Building Blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: failed step
        run: |
          echo "Goodbye, World!"
          exit 0
      - name: This step will be skipped if the previous step fails
        run: echo "This step will be skipped if the previous step failed."